apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/zalando/postgres-operator/master/manifests/operatorconfiguration.crd.yaml
  - https://raw.githubusercontent.com/zalando/postgres-operator/master/manifests/postgresql.crd.yaml
  - https://raw.githubusercontent.com/zalando/postgres-operator/master/manifests/postgresteam.crd.yaml
  - https://raw.githubusercontent.com/zalando/postgres-operator/master/manifests/operator-service-account-rbac.yaml
  - https://raw.githubusercontent.com/zalando/postgres-operator/master/manifests/api-service.yaml
  - https://raw.githubusercontent.com/zalando/postgres-operator/master/manifests/postgres-operator.yaml
  - https://raw.githubusercontent.com/zalando/postgres-operator/master/manifests/postgresql-operator-default-configuration.yaml
