apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/zalando/postgres-operator/master/manifests/operatorconfiguration.crd.yaml
  - https://raw.githubusercontent.com/zalando/postgres-operator/master/manifests/postgresql.crd.yaml
  - https://raw.githubusercontent.com/zalando/postgres-operator/master/manifests/postgresteam.crd.yaml
  - https://raw.githubusercontent.com/zalando/postgres-operator/master/manifests/operator-service-account-rbac.yaml
  - https://raw.githubusercontent.com/zalando/postgres-operator/master/manifests/api-service.yaml
  - https://raw.githubusercontent.com/zalando/postgres-operator/master/manifests/postgres-operator.yaml
  - https://raw.githubusercontent.com/zalando/postgres-operator/master/manifests/postgresql-operator-default-configuration.yaml
  - https://raw.githubusercontent.com/zalando/postgres-operator/master/manifests/minimal-postgres-manifest.yaml

helmCharts:
  - name: postgres-operator
    repo: https://github.com/zalando/postgres-operator/tree/04f18b9716153a664b564f7fc04fbb264617492d/charts/postgres-operator
    version: "*"
    includeCRDs: true
    valuesInline:
