apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgresql.yaml
  - pgsodium-root-key.yaml
  - init-supabase.job.yaml

configurations:
  - kustomize.configuration.yaml
