on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GH_SUDO_PAT }}
  GITHUB_USER: ${{ github.actor }}

jobs:
  build-postgres:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.GITHUB_USER }}
          password: ${{ env.GITHUB_TOKEN }}
      - id: meta
        name: Prepare metadata for Docker image
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/beaglesinspace/supabase-spilo/postgres
          tags: |
            type=edge
            type=sha,enable=true
            type=schedule,pattern={{date 'YYYYMMDD'}}
      - id: build
        name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            spilo_image=ghcr.io/beaglesinspace/supabase-spilo/spilo-focal:edge
            supabase_extensions_image=ghcr.io/beaglesinspace/supabase-spilo/extensions:edge
          push: true
      - id: image_ref
        name: Image full reference
        run: |-
          echo "result=${{ fromJSON(steps.meta.outputs.json).tags[0] }}" >> "${GITHUB_OUTPUT}"

  build-migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.GITHUB_USER }}
          password: ${{ env.GITHUB_TOKEN }}
      - id: meta
        name: Prepare metadata for Docker image
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/beaglesinspace/supabase-spilo/migrations
          tags: |
            type=edge
            type=sha,enable=true
            type=schedule,pattern={{date 'YYYYMMDD'}}
      - id: build
        name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          file: Dockerfile.migrations
          target: migrations
      - id: meta_sidecar
        name: Prepare metadata for Docker image
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/beaglesinspace/supabase-spilo/migrations-sidecar
          tags: |
            type=edge
            type=sha,enable=true
            type=schedule,pattern={{date 'YYYYMMDD'}}
      - id: build_sidecar
        name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          tags: ${{ steps.meta_sidecar.outputs.tags }}
          labels: ${{ steps.meta_sidecar.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          file: Dockerfile.migrations
          target: migrations-sidecar
