on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GH_SUDO_PAT }}
  GITHUB_USER: ${{ github.actor }}

jobs:
  build-base:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build-base.outputs.image }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.GITHUB_USER }}
          password: ${{ env.GITHUB_TOKEN }}

      - id: meta
        name: Prepare metadata for Docker image
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/beaglesinspace/supabase-spilo/focal-python3-10
          tags: |
            type=sha,enable=true

      - id: build_and_push
        name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ !env.ACT }}

      - id: image_ref
        name: get built image ref
        run: |-
          echo "result=${{ fromJSON(steps.meta.outputs.json).tags[0] }}" >> "${GITHUB_OUTPUT}"
