on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GH_SUDO_PAT }}
  GITHUB_USER: ${{ github.actor }}

jobs:
  build-base:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.image_ref.outputs.result }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.GITHUB_USER }}
          password: ${{ env.GITHUB_TOKEN }}
      - id: meta
        name: Prepare metadata for Docker image
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/beaglesinspace/supabase-spilo/focal-python3-10
          tags: |
            type=sha,enable=true
      - id: build_and_export
        name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: Dockerfile.focal-python3-10
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=/tmp/focal-base.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: base
          path: /tmp/focal-base.tar
      - id: image_ref
        name: Image full reference
        run: |-
          echo "result=${{ fromJSON(steps.meta.outputs.json).tags[0] }}" >> "${GITHUB_OUTPUT}"

  build-extensions:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.image_ref.outputs.result }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.GITHUB_USER }}
          password: ${{ env.GITHUB_TOKEN }}
      - id: meta
        name: Prepare metadata for Docker image
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/beaglesinspace/supabase-spilo/extensions
          tags: |
            type=sha,enable=true
      - id: build_and_export
        name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: ./postgres
          target: extensions
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=/tmp/extensions.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: extensions
          path: /tmp/extensions.tar
      - id: image_ref
        name: Image full reference
        run: |-
          echo "result=${{ fromJSON(steps.meta.outputs.json).tags[0] }}" >> "${GITHUB_OUTPUT}"

  build-spilo:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.image_ref.outputs.result }}
    needs:
      - build-base
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.GITHUB_USER }}
          password: ${{ env.GITHUB_TOKEN }}
      - id: meta
        name: Prepare metadata for Docker image
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/beaglesinspace/supabase-spilo/spilo-focal
          tags: |
            type=sha,enable=true
      - name: Download base image
        uses: actions/download-artifact@v3
        with:
          name: focal-base
          path: /tmp
      - name: Load image from artifact
        run: |-
          docker load -i /tmp/focal-base.tar
      - id: build_and_export
        name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: ./spilo/postgres-appliance
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BASE_IMAGE=${{ needs.build-base.outputs.image }}
            DEB_PG_SUPPORTED_VERSIONS="15"
            TIMESCALEDB=2.11.0
          outputs: type=docker,dest=/tmp/spilo.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: spilo
          path: /tmp/spilo.tar
      - id: image_ref
        name: Image full reference
        run: |-
          echo "result=${{ fromJSON(steps.meta.outputs.json).tags[0] }}" >> "${GITHUB_OUTPUT}"

  build-postgres:
    runs-on: ubuntu-latest
    needs:
      - build-spilo
      - build-extensions
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.GITHUB_USER }}
          password: ${{ env.GITHUB_TOKEN }}
      - id: meta
        name: Prepare metadata for Docker image
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/beaglesinspace/supabase-spilo/postgres
          tags: |
            type=sha,enable=true
            type=schedule,pattern={{date 'YYYYMMDD-hhmmss'}}
      - name: Download images
        uses: actions/download-artifact@v3
        with:
          path: /tmp
      - name: Load image from artifact
        run: |-
          docker load -i /tmp/spilo.tar
          docker load -i /tmp/extensions.tar
          docker image ls -a
      - id: build_and_push
        name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            spilo_image=${{ needs.build-spilo.outputs.image }}
            supabase_extensions_image=${{ needs.build-extensions.outputs.image }}
          push: true
      - id: image_ref
        name: Image full reference
        run: |-
          echo "result=${{ fromJSON(steps.meta.outputs.json).tags[0] }}" >> "${GITHUB_OUTPUT}"
